/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  // Force-generate primary color classes regardless of JIT scan state
  safelist: [
    'bg-primary', 'text-primary', 'border-primary', 'fill-primary', 'stroke-primary',
    'bg-primary/5', 'bg-primary/10', 'bg-primary/20',
    'text-primary/80', 'border-primary/10', 'border-primary/20',
    'shadow-primary', 'ring-primary', 'ring-primary/5', 'ring-primary/20',
    'from-primary', 'to-primary', 'via-primary',
    'hover:bg-primary', 'hover:text-primary', 'focus:border-primary',
    'focus:ring-primary', 'active:bg-primary',
    'selection:bg-primary/20', 'selection:text-primary',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006a65",
        "accent": "#2FA7A0",
        "primary-container": "#2fa7a0",
        "on-tertiary-fixed-variant": "#773213",
        "surface-bright": "#fcf9f4",
        "secondary-fixed-dim": "#ffb3ae",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdad7",
        "on-secondary-fixed": "#3c0709",
        "on-secondary-container": "#7a3634",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#87f5ec",
        "on-surface-variant": "#3d4948",
        "surface-container-highest": "#e5e2dd",
        "surface-dim": "#dcdad5",
        "on-background": "#1c1c19",
        "on-error-container": "#93000a",
        "tertiary": "#954928",
        "secondary": "#914946",
        "tertiary-fixed-dim": "#ffb599",
        "on-error": "#ffffff",
        "on-tertiary-container": "#581b00",
        "on-primary-fixed-variant": "#00504c",
        "surface-tint": "#006a65",
        "tertiary-fixed": "#ffdbce",
        "outline": "#6d7a78",
        "primary-fixed-dim": "#6ad8d0",
        "inverse-primary": "#6ad8d0",
        "outline-variant": "#E6E0D7",
        "on-surface-variant": "#6D7A78",
        "background": "#FAF7F2",
        "on-surface": "#1c1c19",
        "surface-container-low": "#f6f3ee",
        "inverse-on-surface": "#f3f0eb",
        "on-primary-fixed": "#00201e",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffa39e",
        "error-container": "#ffdad6",
        "surface-container": "#f0ede9",
        "surface": "#fcf9f4",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#370e00",
        "inverse-surface": "#31302d",
        "tertiary-container": "#da7f5a",
        "on-primary-container": "#003633",
        "on-secondary-fixed-variant": "#743230",
        "surface-container-high": "#ebe8e3",
        "surface-variant": "#e5e2dd"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}
