import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import OpenAI from 'openai';
import { resolveHoliday } from './holidays.data';

/** Структура дневного пакета, возвращаемого AI */
export interface AiDailyPack {
  horoscope: string;
  horoscopeDetailed: string;
  advice: string;
  moon: string;
  aspect: string;
  holiday: string | null;
  supportPhrase: string;
}

/** Контекст для генерации пакета */
export interface PromptContext {
  zodiacSign: string;
  mood: string;
  gender: string;
  date: string;
}

// ─── Structured Output schemas (strict: true) ───────────────────────────────

const DAILY_PACK_SCHEMA = {
  type: 'json_schema' as const,
  json_schema: {
    name: 'daily_pack',
    strict: true,
    schema: {
      type: 'object',
      properties: {
        horoscope:         { type: 'string' },
        horoscopeDetailed: { type: 'string' },
        advice:            { type: 'string' },
        moon:              { type: 'string' },
        aspect:            { type: 'string' },
        supportPhrase:     { type: 'string' },
      },
      required: ['horoscope', 'horoscopeDetailed', 'advice', 'moon', 'aspect', 'supportPhrase'],
      additionalProperties: false,
    },
  },
};

// holiday is always resolved locally — not generated by the LLM.
const SUPPORT_PHRASE_SCHEMA = {
  type: 'json_schema' as const,
  json_schema: {
    name: 'support_phrase',
    strict: true,
    schema: {
      type: 'object',
      properties: {
        supportPhrase: { type: 'string' },
      },
      required: ['supportPhrase'],
      additionalProperties: false,
    },
  },
};

const LLM_MODEL = 'gpt-5.4-mini-2026-03-17' as const;

@Injectable()
export class AiService {
  private readonly logger = new Logger(AiService.name);
  private readonly openai: OpenAI | null;

  constructor(private readonly config: ConfigService) {
    const apiKey = this.config.get<string>('AI_API_KEY');
    this.openai = apiKey ? new OpenAI({ apiKey }) : null;
    if (!this.openai) {
      this.logger.warn('AI_API_KEY not set — running in mock fallback mode');
    }
  }

  // ─── Mock horoscope bank (Fallback Policy) — all 12 signs ────────────────
  private readonly horoscopes: Record<
    string,
    { main: string; detailed: string; advice: string; moon: string; aspect: string }
  > = {
    'Овен ♈︎': {
      main:     'Сегодня день решительных действий. Ваша энергия на пике — используйте её для важных начинаний.',
      detailed: 'Марс активно влияет на ваш знак, придавая мощную внутреннюю силу. Планеты поддерживают смелые решения и новые старты. Не бойтесь брать инициативу в свои руки.',
      advice:   'Действуйте смело, но избегайте конфликтов — сила в спокойствии.',
      moon:     'Растущая Луна усиливает вашу интуицию и напор.',
      aspect:   'Марс в тригоне с Юпитером — удача на вашей стороне.',
    },
    'Телец ♉︎': {
      main:     'Финансовые вопросы выходят на первый план. Присмотритесь к новым возможностям для стабильности.',
      detailed: 'Венера благоволит стабильности и накоплению. Сегодня хороший день для долгосрочных инвестиций, планирования и заботы о комфорте. Доверяйте своей интуиции в вопросах материального.',
      advice:   'Не торопитесь с крупными тратами — взвесьте всё дважды.',
      moon:     'Луна в вашем знаке — время самозаботы и отдыха.',
      aspect:   'Венера секстиль Сатурн — надёжность и стабильность во всём.',
    },
    'Близнецы ♊︎': {
      main:     'Коммуникация — ваш главный инструмент сегодня. Важный разговор может изменить всё.',
      detailed: 'Меркурий усиливает ваше красноречие и любознательность. Используйте слова как мост к новым возможностям. Сегодня особенно продуктивны переговоры и обмен идеями.',
      advice:   'Слушайте больше, чем говорите — так вы узнаете самое важное.',
      moon:     'Луна в воздушном знаке дарит лёгкость в общении.',
      aspect:   'Меркурий конъюнкция Солнце — ясность мысли и красноречие.',
    },
    'Рак ♋︎': {
      main:     'Сегодня особенно важны близкие отношения и домашний уют. Прислушайтесь к своему сердцу.',
      detailed: 'Луна — ваш покровитель — усиливает эмоциональную чуткость. Это время для глубоких разговоров с близкими, для заботы и принятия. Не закрывайтесь от тех, кто нуждается в вас.',
      advice:   'Позвольте себе быть уязвимым — это даёт силу, а не слабость.',
      moon:     'Луна в родном знаке усиливает интуицию и эмпатию.',
      aspect:   'Луна трин Нептун — мечты становятся ближе к реальности.',
    },
    'Лев ♌︎': {
      main:     'Ваше сияние сегодня особенно заметно окружающим. Время для творчества и самовыражения.',
      detailed: 'Солнце наполняет вас уверенностью и магнетизмом. Люди тянутся к вашей энергии. Используйте этот день для реализации творческих идей и укрепления своего авторитета.',
      advice:   'Щедро делитесь своим светом — и он вернётся к вам сторицей.',
      moon:     'Растущая Луна усиливает вашу харизму и притяжение.',
      aspect:   'Солнце секстиль Юпитер — расширение возможностей и удача.',
    },
    'Дева ♍︎': {
      main:     'День подходит для анализа, планирования и наведения порядка — в делах и в голове.',
      detailed: 'Меркурий активизирует вашу природную аналитичность. Детали, которые другие пропустят, вы заметите сразу. Этот день идеален для систематизации, решения задач и заботы о здоровье.',
      advice:   'Не перфекционируйте до бесконечности — завершённое лучше идеального.',
      moon:     'Луна в земном знаке призывает к практичности и порядку.',
      aspect:   'Меркурий квадрат Сатурн — внимание к деталям принесёт плоды.',
    },
    'Весы ♎︎': {
      main:     'Гармония и баланс — ваши ключевые темы сегодня. Ищите компромисс там, где раньше виделся конфликт.',
      detailed: 'Венера освещает ваши отношения и эстетическое восприятие мира. Сегодня легко находить красоту и справедливость вокруг. Особенно благоприятны партнёрства и совместные начинания.',
      advice:   'Доверяйте своей интуиции при выборе — она подскажет верный путь.',
      moon:     'Луна в воздушном знаке гармонизирует отношения.',
      aspect:   'Венера трин Луна — эмоциональный баланс и тепло в отношениях.',
    },
    'Скорпион ♏︎': {
      main:     'Сегодня вы чувствуете глубину происходящего острее обычного. Время трансформации и открытий.',
      detailed: 'Плутон усиливает вашу проницательность и волю к переменам. Скрытые мотивы станут очевидны, а глубокие разговоры принесут ясность. Не бойтесь идти туда, где другие останавливаются.',
      advice:   'Отпустите то, что уже не служит вам — освободите место для нового.',
      moon:     'Луна усиливает интуицию и магнетизм вашего знака.',
      aspect:   'Плутон секстиль Марс — трансформирующая сила и решимость.',
    },
    'Стрелец ♐︎': {
      main:     'Оптимизм и тяга к новому — ваши союзники сегодня. Горизонты расширяются.',
      detailed: 'Юпитер дарит вам щедрость судьбы и широту взглядов. Новые идеи, путешествия (даже мысленные) и обучение принесут радость. Ваш энтузиазм заразителен — делитесь им.',
      advice:   'Мечтайте масштабно, но делайте первый шаг уже сегодня.',
      moon:     'Растущая Луна зажигает дух приключений.',
      aspect:   'Юпитер трин Солнце — удача и расширение возможностей.',
    },
    'Козерог ♑︎': {
      main:     'Упорство и дисциплина сегодня вознаграждаются. Ваши усилия не останутся незамеченными.',
      detailed: 'Сатурн укрепляет вашу решимость и строит прочный фундамент. Профессиональные вопросы решаются успешно. Долгосрочные планы, начатые сегодня, принесут стабильный результат.',
      advice:   'Не сравнивайте свой путь с чужим — ваш темп именно таков, каким должен быть.',
      moon:     'Луна в земном знаке призывает к терпению и структуре.',
      aspect:   'Сатурн секстиль Меркурий — стратегическое мышление на высоте.',
    },
    'Водолей ♒︎': {
      main:     'Нестандартные идеи и свежий взгляд — ваши козыри сегодня. Не бойтесь быть собой.',
      detailed: 'Уран активизирует ваш ум и тягу к переменам. Коллективные проекты и инновации в центре внимания. Ваша способность видеть будущее сегодня особенно сильна — доверяйте ей.',
      advice:   'Объединяйтесь с единомышленниками — вместе вы сдвинете горы.',
      moon:     'Луна в воздушном знаке пробуждает оригинальность мышления.',
      aspect:   'Уран квинкункс Солнце — неожиданные инсайты и открытия.',
    },
    'Рыбы ♓︎': {
      main:     'Интуиция сегодня говорит громче разума. Прислушайтесь к своим внутренним сигналам.',
      detailed: 'Нептун открывает вашу чуткость к тонким энергиям мира. Творчество, медитация и духовные практики принесут глубокое удовлетворение. Граница между мечтой и реальностью сегодня очень тонка.',
      advice:   'Выделите время для тишины и восстановления — это ваш источник силы.',
      moon:     'Луна усиливает вашу эмпатию и восприимчивость.',
      aspect:   'Нептун трин Венера — вдохновение, красота и душевный покой.',
    },
  };

  // ─── Mock support phrases (Fallback Policy) ───────────────────────────────
  // Keys = canonical mood IDs (feminine forms — base in DB).
  private readonly supportPhrases: Record<string, string[]> = {
    Спокойна: [
      'Ты на правильном пути. Каждый шаг имеет значение.',
      'Сегодня прекрасный день, чтобы просто быть собой.',
      'Спокойствие — это суперсила. Ты уже всё знаешь.',
      'Тишина внутри — лучший советчик.',
      'Доверься потоку. Всё происходит вовремя.',
    ],
    Нормально: [
      'Иногда «нормально» — это уже маленькая победа.',
      'Ровный день — лучшая основа для глубоких решений.',
      'Не каждый день должен быть ярким. И в этом тоже сила.',
      'Сегодня можно просто быть. Без подвигов.',
      'Баланс — это то, что ты создаёшь прямо сейчас.',
    ],
    Устала: [
      'Отдых — это не слабость, а мудрость. Позволь себе восстановиться.',
      'Даже самые сильные деревья склоняются перед ветром.',
      'Сегодня можно просто быть. Без подвигов. Без рекордов.',
      'Усталость — знак, что ты много отдала миру.',
      'Закрой глаза. Мир подождёт.',
    ],
    Тревожна: [
      'Вдохни глубоко. Ты в безопасности прямо сейчас.',
      'Тревога лжёт. Реальность добрее, чем кажется.',
      'Шаг за шагом. Не нужно решать всё сразу.',
      'Ты справлялась раньше — справишься и сейчас.',
      'Эта волна пройдёт. Ты крепче, чем она.',
    ],
    Грустна: [
      'Грусть — это не слабость. Это глубина твоей души.',
      'После дождя всегда выходит солнце. Подожди немного.',
      'Ты сильнее, чем думаешь. Это пройдёт.',
      'Разреши себе чувствовать — это нормально и важно.',
      'Каждая слеза поливает семена будущей радости.',
    ],
    Воодушевлена: [
      'Твоя энергия сегодня — подарок миру. Делись ею.',
      'Когда сердце поёт — весь мир танцует с тобой.',
      'Сегодня — идеальный день, чтобы начать то, о чём мечтаешь.',
      'Ты — магнит для чудес. Доверяй своей внутренней силе.',
      'Запомни этот момент. Ты создаёшь счастье прямо сейчас.',
    ],
  };

  // ─── Holidays: resolved locally (never by LLM), always returns a value ──
  // Real holiday → from HOLIDAYS_FULL dict; otherwise → wellness theme rotation.
  // See backend/src/ai/holidays.data.ts for the full calendar.

  // ─────────────────────────────────────────────────────────────────────────
  // generateDailyPack — Full Pack
  // try: OpenAI Structured Outputs → merge local holiday
  // catch: log error → return mock fallback (app never throws)
  // ─────────────────────────────────────────────────────────────────────────
  async generateDailyPack(
    userId: string,
    context: PromptContext,
  ): Promise<AiDailyPack> {
    this.logger.log(
      `generateDailyPack user=${userId}, sign=${context.zodiacSign}, mood=${context.mood}`,
    );

    if (this.openai) {
      try {
        const completion = await this.openai.chat.completions.create({
          model: LLM_MODEL,
          temperature: 0.3,
          response_format: DAILY_PACK_SCHEMA,
          messages: [
            {
              role: 'system',
              content:
                'Ты — профессиональный астрологический ИИ. Генерируй персонализированный контент на русском языке строго по JSON-схеме. Без вступлений и пояснений.',
            },
            {
              role: 'user',
              content:
                `Знак зодиака: ${context.zodiacSign}. Текущее настроение: ${context.mood}. Пол: ${context.gender}. Дата: ${context.date}.\n\n` +
                'Сгенерируй:\n' +
                '- horoscope: главный прогноз дня (2–3 предложения, вдохновляющий тон)\n' +
                '- horoscopeDetailed: расширенный астрологический прогноз с упоминанием планет (3–4 предложения)\n' +
                '- advice: практический совет на день (1–2 предложения)\n' +
                '- moon: лунная фаза и её влияние сегодня (1 предложение)\n' +
                '- aspect: ключевой планетарный аспект дня (1 предложение)\n' +
                `- supportPhrase: тёплая фраза поддержки с учётом настроения "${context.mood}" (1–2 предложения)`,
            },
          ],
        });

        const raw = completion.choices[0]?.message?.content ?? '';
        const parsed = JSON.parse(raw) as {
          horoscope: string;
          horoscopeDetailed: string;
          advice: string;
          moon: string;
          aspect: string;
          supportPhrase: string;
        };

        const holiday = resolveHoliday(context.date);
        this.logger.log(
          `generateDailyPack LLM OK, tokens=${completion.usage?.total_tokens ?? '?'}`,
        );

        return { ...parsed, holiday: holiday.name };
      } catch (err) {
        this.logger.error(
          'generateDailyPack LLM failed — using fallback',
          (err as Error).message,
        );
      }
    }

    // ── Fallback: mock dictionaries ──────────────────────────────────────────
    const horoscope =
      this.horoscopes[context.zodiacSign] ?? this.horoscopes['Овен ♈︎'];
    const phrases =
      this.supportPhrases[context.mood] ?? this.supportPhrases['Нормально'];
    const holiday = resolveHoliday(context.date);

    return {
      horoscope:         horoscope.main,
      horoscopeDetailed: horoscope.detailed,
      advice:            horoscope.advice,
      moon:              horoscope.moon,
      aspect:            horoscope.aspect,
      holiday:           holiday.name,
      supportPhrase:     phrases[Math.floor(Math.random() * phrases.length)],
    };
  }

  // ─────────────────────────────────────────────────────────────────────────
  // updateMoodSupport — Hybrid Partial Update (mood changed, only support changes)
  // Lightweight single-field LLM call; falls back to mock phrase on any error.
  // ─────────────────────────────────────────────────────────────────────────
  async updateMoodSupport(
    userId: string,
    newMood: string,
  ): Promise<{ supportPhrase: string }> {
    this.logger.log(`updateMoodSupport user=${userId}, mood=${newMood}`);

    if (this.openai) {
      try {
        const completion = await this.openai.chat.completions.create({
          model: LLM_MODEL,
          temperature: 0.5,
          response_format: SUPPORT_PHRASE_SCHEMA,
          messages: [
            {
              role: 'system',
              content:
                'Ты — эмпатичный генератор фраз поддержки на русском языке. Отвечай строго по JSON-схеме. Без вступлений.',
            },
            {
              role: 'user',
              content:
                `Текущее настроение пользователя: ${newMood}. ` +
                'Напиши одну тёплую фразу поддержки (1–2 предложения), которая принимает это состояние и мягко вдохновляет двигаться вперёд.',
            },
          ],
        });

        const raw = completion.choices[0]?.message?.content ?? '';
        const parsed = JSON.parse(raw) as { supportPhrase: string };
        this.logger.log('updateMoodSupport LLM OK');
        return { supportPhrase: parsed.supportPhrase };
      } catch (err) {
        this.logger.error(
          'updateMoodSupport LLM failed — using fallback',
          (err as Error).message,
        );
      }
    }

    // ── Fallback ─────────────────────────────────────────────────────────────
    const phrases =
      this.supportPhrases[newMood] ?? this.supportPhrases['Нормально'];
    return {
      supportPhrase: phrases[Math.floor(Math.random() * phrases.length)],
    };
  }
}
