import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import OpenAI from 'openai';
import { resolveHoliday } from './holidays.data';

/** Структура дневного пакета, возвращаемого AI */
export interface AiDailyPack {
  horoscope: string;
  horoscopeDetailed: string;
  advice: string;
  moon: string;
  aspect: string;
  holiday: string | null;
  supportPhrase: string;
}

/** Контекст для генерации пакета */
export interface PromptContext {
  zodiacSign: string;
  mood: string;
  gender: string;
  date: string;
}

// ─── Structured Output schemas (strict: true) ───────────────────────────────

const DAILY_PACK_SCHEMA = {
  type: 'json_schema' as const,
  json_schema: {
    name: 'daily_pack',
    strict: true,
    schema: {
      type: 'object',
      properties: {
        horoscope:         { type: 'string' },
        horoscopeDetailed: { type: 'string' },
        advice:            { type: 'string' },
        moon:              { type: 'string' },
        aspect:            { type: 'string' },
        supportPhrase:     { type: 'string' },
      },
      required: ['horoscope', 'horoscopeDetailed', 'advice', 'moon', 'aspect', 'supportPhrase'],
      additionalProperties: false,
    },
  },
};

// holiday is always resolved locally — not generated by the LLM.
const SUPPORT_PHRASE_SCHEMA = {
  type: 'json_schema' as const,
  json_schema: {
    name: 'support_phrase',
    strict: true,
    schema: {
      type: 'object',
      properties: {
        supportPhrase: { type: 'string' },
      },
      required: ['supportPhrase'],
      additionalProperties: false,
    },
  },
};

const LLM_MODEL = 'gpt-5.4-mini-2026-03-17' as const;

@Injectable()
export class AiService {
  private readonly logger = new Logger(AiService.name);
  private readonly openai: OpenAI | null;

  constructor(private readonly config: ConfigService) {
    const apiKey = this.config.get<string>('AI_API_KEY');
    this.openai = apiKey ? new OpenAI({ apiKey }) : null;
    if (!this.openai) {
      this.logger.warn('AI_API_KEY not set — running in mock fallback mode');
    }
  }

  // ─── Mock horoscope bank (Fallback Policy) ────────────────────────────────
  private readonly horoscopes: Record<
    string,
    { main: string; detailed: string; advice: string; moon: string; aspect: string }
  > = {
    'Овен ♈︎': {
      main:     'Сегодня день решительных действий. Ваша энергия на пике — используйте её для важных начинаний.',
      detailed: 'Марс активно влияет на ваш знак, придавая мощную внутреннюю силу. Не бойтесь брать инициативу.',
      advice:   'Действуйте смело, но избегайте конфликтов — сила в спокойствии.',
      moon:     'Растущая Луна усиливает вашу интуицию.',
      aspect:   'Марс в тригоне с Юпитером — удача на вашей стороне.',
    },
    'Телец ♉︎': {
      main:     'Финансовые вопросы выходят на первый план. Присмотритесь к новым возможностям.',
      detailed: 'Венера благоволит стабильности. Сегодня хороший день для долгосрочных инвестиций и планирования.',
      advice:   'Не торопитесь с крупными тратами — подождите пару дней.',
      moon:     'Луна в вашем знаке — время самозаботы.',
      aspect:   'Венера секстиль Сатурн — надёжность во всём.',
    },
    'Близнецы ♊︎': {
      main:     'Коммуникация — ваш главный инструмент сегодня. Важный разговор может изменить всё.',
      detailed: 'Меркурий усиливает ваше красноречие. Используйте слова как мост к новым возможностям.',
      advice:   'Слушайте больше, чем говорите — так вы узнаете главное.',
      moon:     'Луна в воздушном знаке — лёгкость в общении.',
      aspect:   'Меркурий конъюнкция Солнце — ясность мысли.',
    },
  };

  // ─── Mock support phrases (Fallback Policy) ───────────────────────────────
  // Keys = canonical mood IDs (feminine forms — base in DB).
  private readonly supportPhrases: Record<string, string[]> = {
    Спокойна: [
      'Ты на правильном пути. Каждый шаг имеет значение.',
      'Сегодня прекрасный день, чтобы просто быть собой.',
      'Спокойствие — это суперсила. Ты уже всё знаешь.',
      'Тишина внутри — лучший советчик.',
      'Доверься потоку. Всё происходит вовремя.',
    ],
    Нормально: [
      'Иногда «нормально» — это уже маленькая победа.',
      'Ровный день — лучшая основа для глубоких решений.',
      'Не каждый день должен быть ярким. И в этом тоже сила.',
      'Сегодня можно просто быть. Без подвигов.',
      'Баланс — это то, что ты создаёшь прямо сейчас.',
    ],
    Устала: [
      'Отдых — это не слабость, а мудрость. Позволь себе восстановиться.',
      'Даже самые сильные деревья склоняются перед ветром.',
      'Сегодня можно просто быть. Без подвигов. Без рекордов.',
      'Усталость — знак, что ты много отдала миру.',
      'Закрой глаза. Мир подождёт.',
    ],
    Тревожна: [
      'Вдохни глубоко. Ты в безопасности прямо сейчас.',
      'Тревога лжёт. Реальность добрее, чем кажется.',
      'Шаг за шагом. Не нужно решать всё сразу.',
      'Ты справлялась раньше — справишься и сейчас.',
      'Эта волна пройдёт. Ты крепче, чем она.',
    ],
    Грустна: [
      'Грусть — это не слабость. Это глубина твоей души.',
      'После дождя всегда выходит солнце. Подожди немного.',
      'Ты сильнее, чем думаешь. Это пройдёт.',
      'Разреши себе чувствовать — это нормально и важно.',
      'Каждая слеза поливает семена будущей радости.',
    ],
    Воодушевлена: [
      'Твоя энергия сегодня — подарок миру. Делись ею.',
      'Когда сердце поёт — весь мир танцует с тобой.',
      'Сегодня — идеальный день, чтобы начать то, о чём мечтаешь.',
      'Ты — магнит для чудес. Доверяй своей внутренней силе.',
      'Запомни этот момент. Ты создаёшь счастье прямо сейчас.',
    ],
  };

  // ─── Holidays: resolved locally (never by LLM), always returns a value ──
  // Real holiday → from HOLIDAYS_FULL dict; otherwise → wellness theme rotation.
  // See backend/src/ai/holidays.data.ts for the full calendar.

  // ─────────────────────────────────────────────────────────────────────────
  // generateDailyPack — Full Pack
  // try: OpenAI Structured Outputs → merge local holiday
  // catch: log error → return mock fallback (app never throws)
  // ─────────────────────────────────────────────────────────────────────────
  async generateDailyPack(
    userId: string,
    context: PromptContext,
  ): Promise<AiDailyPack> {
    this.logger.log(
      `generateDailyPack user=${userId}, sign=${context.zodiacSign}, mood=${context.mood}`,
    );

    if (this.openai) {
      try {
        const completion = await this.openai.chat.completions.create({
          model: LLM_MODEL,
          temperature: 0.3,
          response_format: DAILY_PACK_SCHEMA,
          messages: [
            {
              role: 'system',
              content:
                'Ты — астрологический API-модуль. Отдавай только JSON строго по схеме. Без пояснений.',
            },
            {
              role: 'user',
              content:
                `Знак зодиака: ${context.zodiacSign}. ` +
                `Настроение: ${context.mood}. ` +
                `Пол: ${context.gender}. ` +
                `Дата: ${context.date}. ` +
                `Сгенерируй персональный гороскоп и вдохновляющую фразу поддержки на русском языке.`,
            },
          ],
        });

        const raw = completion.choices[0]?.message?.content ?? '';
        const parsed = JSON.parse(raw) as {
          horoscope: string;
          horoscopeDetailed: string;
          advice: string;
          moon: string;
          aspect: string;
          supportPhrase: string;
        };

        const holiday = resolveHoliday(context.date);
        this.logger.log(
          `generateDailyPack LLM OK, tokens=${completion.usage?.total_tokens ?? '?'}`,
        );

        return { ...parsed, holiday: holiday.name };
      } catch (err) {
        this.logger.error(
          'generateDailyPack LLM failed — using fallback',
          (err as Error).message,
        );
      }
    }

    // ── Fallback: mock dictionaries ──────────────────────────────────────────
    const horoscope =
      this.horoscopes[context.zodiacSign] ?? this.horoscopes['Овен ♈︎'];
    const phrases =
      this.supportPhrases[context.mood] ?? this.supportPhrases['Нормально'];
    const holiday = resolveHoliday(context.date);

    return {
      horoscope:         horoscope.main,
      horoscopeDetailed: horoscope.detailed,
      advice:            horoscope.advice,
      moon:              horoscope.moon,
      aspect:            horoscope.aspect,
      holiday:           holiday.name,
      supportPhrase:     phrases[Math.floor(Math.random() * phrases.length)],
    };
  }

  // ─────────────────────────────────────────────────────────────────────────
  // updateMoodSupport — Hybrid Partial Update (mood changed, only support changes)
  // Lightweight single-field LLM call; falls back to mock phrase on any error.
  // ─────────────────────────────────────────────────────────────────────────
  async updateMoodSupport(
    userId: string,
    newMood: string,
  ): Promise<{ supportPhrase: string }> {
    this.logger.log(`updateMoodSupport user=${userId}, mood=${newMood}`);

    if (this.openai) {
      try {
        const completion = await this.openai.chat.completions.create({
          model: LLM_MODEL,
          temperature: 0.5,
          response_format: SUPPORT_PHRASE_SCHEMA,
          messages: [
            {
              role: 'system',
              content:
                'Ты — генератор фраз поддержки. Отдавай только JSON строго по схеме. Без пояснений.',
            },
            {
              role: 'user',
              content:
                `Настроение пользователя: ${newMood}. ` +
                `Напиши одну короткую вдохновляющую фразу поддержки на русском языке.`,
            },
          ],
        });

        const raw = completion.choices[0]?.message?.content ?? '';
        const parsed = JSON.parse(raw) as { supportPhrase: string };
        this.logger.log('updateMoodSupport LLM OK');
        return { supportPhrase: parsed.supportPhrase };
      } catch (err) {
        this.logger.error(
          'updateMoodSupport LLM failed — using fallback',
          (err as Error).message,
        );
      }
    }

    // ── Fallback ─────────────────────────────────────────────────────────────
    const phrases =
      this.supportPhrases[newMood] ?? this.supportPhrases['Нормально'];
    return {
      supportPhrase: phrases[Math.floor(Math.random() * phrases.length)],
    };
  }
}
